function snapshot_4way_fs6(input_path_lh,input_path_rh,fmin,fmax,state)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
cmd = ['tksurferfv fsaverage6 lh ' state ' -overlay ',input_path_lh,' -fminmax  ' num2str(fmin),32,num2str(fmax),...
        '  -colscalebarflag 0 -invphaseflag 0 -tcl /home/eyre/pic-generate/test_lat.tcl;',...
        'mv 1.tiff ',input_path_lh,'_fs6_' state '_' num2str(fmin) '_' num2str(fmax) '.tiff'];
    system(cmd);
    
    cmd = ['tksurferfv fsaverage6 lh ' state ' -overlay ',input_path_lh,' -fminmax  ' num2str(fmin),32,num2str(fmax),...
        '  -colscalebarflag 0 -invphaseflag 0 -tcl /home/eyre/pic-generate/test_med.tcl;',...
        'mv 1.tiff ',input_path_lh,'_fs6_' state '_med_' num2str(fmin) '_' num2str(fmax) '.tiff'];
    system(cmd);
    
    % rh
    cmd = ['tksurferfv fsaverage6 rh ' state ' -overlay ',input_path_rh,' -fminmax  ' num2str(fmin),32,num2str(fmax),...
        '  -colscalebarflag 0 -invphaseflag 0 -tcl /home/eyre/pic-generate/test_lat.tcl;',...
        'mv 1.tiff ',input_path_rh,'_fs6_' state '_' num2str(fmin) '_' num2str(fmax) '.tiff'];
    system(cmd);
    
    cmd = ['tksurferfv fsaverage6 rh ' state ' -overlay ',input_path_rh,' -fminmax  ' num2str(fmin),32,num2str(fmax),...
        '  -colscalebarflag 0 -invphaseflag 0 -tcl /home/eyre/pic-generate/test_med.tcl;',...
        'mv 1.tiff ',input_path_rh,'_fs6_' state '_med_' num2str(fmin) '_' num2str(fmax) '.tiff'];
    system(cmd);
end

